# Generated by Django 4.1.4 on 2023-01-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentMessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentmessages',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intentmessages',
            name='permission',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intentmessages',
            name='senderComponent',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intentmessages',
            name='targetComponent',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intentmessages',
            name='type',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
