# Generated by Django 4.1.4 on 2023-01-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intentMessages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intentmessages',
            old_name='Permission',
            new_name='permission',
        ),
    ]
