# Generated by Django 4.1.4 on 2023-01-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentMessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentmessages',
            name='Permission',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='intentmessages',
            name='senderComponent',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='intentmessages',
            name='targetComponent',
            field=models.CharField(max_length=50),
        ),
    ]
