# Generated by Django 4.1.4 on 2023-01-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameApp', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('size', models.IntegerField()),
                ('app_name', models.CharField(max_length=50)),
                ('app_package', models.CharField(max_length=50)),
                ('app_lable', models.CharField(max_length=50)),
                ('app_icon', models.CharField(max_length=50)),
                ('app_MinSDKVersion', models.CharField(max_length=5)),
                ('app_MaxSDKVersion', models.CharField(max_length=5)),
                ('app_TargetSDKVersion', models.CharField(max_length=5)),
                ('app_AndroidVersionCode', models.CharField(max_length=5)),
                ('app_AndroidVersionName', models.CharField(max_length=5)),
            ],
        ),
    ]
