# Generated by Django 4.1.4 on 2022-12-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='size',
            field=models.IntegerField(),
        ),
    ]
