# Generated by Django 4.1.4 on 2023-01-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_alter_information_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='app_AndroidVersionCode',
            field=models.CharField(default=55, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='app_AndroidVersionName',
            field=models.CharField(default=555, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='app_MaxSDKVersion',
            field=models.CharField(default=777, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='app_MinSDKVersion',
            field=models.CharField(default=666, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='app_TargetSDKVersion',
            field=models.CharField(default=4444, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='app_icon',
            field=models.CharField(default=77, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='app_lable',
            field=models.CharField(default=88, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='app_name',
            field=models.CharField(default=99, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='app_package',
            field=models.CharField(default='kk', max_length=50),
            preserve_default=False,
        ),
    ]
