# Generated by Django 4.1.4 on 2023-01-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAliasComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.IntegerField()),
                ('name', models.CharField(max_length=50, null=True)),
                ('exported', models.BooleanField()),
                ('permissionName', models.CharField(max_length=50)),
                ('filterCheck', models.BooleanField()),
                ('categoriesCheck', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='activityAliasComponents.activityaliascomponents')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
                ('filt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='activityAliasComponents.filter')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionName', models.CharField(max_length=50)),
                ('filt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='activityAliasComponents.filter')),
            ],
        ),
    ]
