# Generated by Django 4.1.4 on 2023-01-20 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityComponents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='activityComponents.activitycomponents')),
            ],
        ),
    ]
