# Generated by Django 4.1.4 on 2023-01-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityComponents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitycomponents',
            old_name='Exported',
            new_name='exported',
        ),
        migrations.RenameField(
            model_name='activitycomponents',
            old_name='PermissionName',
            new_name='permissionName',
        ),
    ]
