# Generated by Django 4.1.4 on 2023-01-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityComponents', '0002_alter_activitycomponents_categoriescheck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycomponents',
            name='permissionName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
