# Generated by Django 4.1.4 on 2023-01-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIPermission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apipermission',
            name='info',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='apipermission',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apipermission',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
